repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        "types": [python]
        require_serial: true
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-duplicate-keys,
            --verbose,
          ]

      - id: isort
        entry: isort
        name: isort
        language: system
        types: [python]
        require_serial: false
        args: ["--line-length", "120", "--profile", "black", "--py", "311"]

      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=120, --target-version=py311, --diff]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        pass_filenames: false

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true
        args: [--ignore-missing-imports]
