version: '3.8'
name: wba
services:
  ad-wba-redis:
    container_name: ad-wba-redis
    image: redis:7.0
    env_file:
      - .env
    volumes:
      - ad-wba-redis-data:/data
    restart: on-failure
    healthcheck:
      test: [ 'CMD', 'redis-cli' ]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - ad-network

  ad-wba-rabbitmq:
    container_name: ad-wba-rabbitmq
    image: rabbitmq:3.11.15-management
    hostname: ad-wba-rabbitmq
    env_file:
      - .env
    expose:
      - "5672"
      - "15672"
    volumes:
      - ad-wba-rabbitmq-data:/var/lib/rabbitmq/
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - ad-network

  ad-wba:
    container_name: ad-wba
    build: ./app
    env_file:
      - .env
    restart: on-failure
    expose:
      - 8000
    depends_on:
      ad-wba-redis:
        condition: service_healthy
    networks:
      - ad-network

  ad-wba-worker:
    container_name: ad-wba-worker
    build: ./app
    env_file:
      - .env
    command: poetry run arq core.arq.WorkerSettings
    restart: on-failure
    depends_on:
      ad-wba-redis:
        condition: service_healthy
    networks:
      - ad-network

volumes:
  ad-wba-redis-data:
  ad-wba-rabbitmq-data:


networks:
  ad-network:
    name: ad-network
    external: true
