name: Code quality checks
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  code-checks:
    runs-on: ubuntu-latest
    env:
      WORKDIR: app
      MYPYPATH: src
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install --upgrade pip && pip install poetry==1.4
          poetry config virtualenvs.in-project true
          poetry install --no-ansi --no-root
      - name: Format with black
        run: |

          poetry run black --diff --check $(git ls-files '*.py')
      - name: Lint with flake8
        run: |
          poetry run flake8 --count --exit-zero --statistics --show-source $(git ls-files '*.py')
      - name: Lint with Mypy
        env:
          MYPYPATH: ${{ env.MYPYPATH }}
        run: |
          poetry run mypy --config-file ../mypy.ini $(git ls-files '*.py')
