name: Docker Image CI
on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:
jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    env:
      WORKDIR: app
      MYPYPATH: src
      OCI_REGISTRY: ${{ vars.DOCKER_REG_URL }}
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker AD
        uses: docker/login-action@v2
        with:
          registry: ${{ env.OCI_REGISTRY }}
          username: ${{ secrets.DOCKERAD_USERNAME }}
          password: ${{ secrets.DOCKERAD_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.WORKDIR }}
          push: true
          tags: |
            ${{ env.OCI_REGISTRY }}/ad/wbadapter:latest
